# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dotenv
        run: npm install dotenv
      - name: Generate env variables
        env:
          SERVER_PORT: ${{secrets.SERVER_PORT}}
          DB_PORT: ${{secrets.DB_PORT}}
          DB_URL: ${{secrets.DB_URL}}
        run: |
          echo "SERVER_PORT=$SERVER_PORT" >> $GITHUB_WORKSPACE/.env
          echo "DB_PORT=$DB_PORT" >> $GITHUB_WORKSPACE/.env
          echo "DB_URL=$DB_URL" >> $GITHUB_WORKSPACE/.env

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
